[server]
port = 8080

[database]
host = "localhost"
port = 5432
user = "your_db_user"
password = "your_db_password"
dbname = "youtube_recommender"
sslmode = "disable"

[oauth]
client_id = "your-google-client-id"
client_secret = "your-google-client-secret"
redirect_url = "http://localhost:8080/auth/google/callback"